fix: Union of TVF leaf operators results in multiple split sources (#26980)
## Description
<!---Describe your changes in detail-->
```
SELECT 
    'Even Numbers' AS sequence_type,
    num AS value
FROM TABLE(sequence(0, 100, 2)) AS t(num)

UNION ALL

SELECT 
    'Multiples of 5' AS sequence_type,
    num AS value
FROM TABLE(sequence(0, 100, 5)) AS t(num)

UNION ALL

SELECT 
    'Multiples of 10' AS sequence_type,
    num AS value
FROM TABLE(sequence(0, 100, 10)) AS t(num)

ORDER BY sequence_type, value;
```

Error:
```
java.lang.IllegalArgumentException: expected one element but was: <0=system:com.facebook.presto.spi.FixedSplitSource@15989fd0, 5=system:com.facebook.presto.spi.FixedSplitSource@4fec0d31, 11=system:com.facebook.presto.spi.FixedSplitSource@7a1c313f>
	at com.google.common.collect.Iterators.getOnlyElement(Iterators.java:323)
	at com.google.common.collect.Iterables.getOnlyElement(Iterables.java:263)
	at com.facebook.presto.execution.scheduler.SectionExecutionFactory.createStageScheduler(SectionExecutionFactory.java:296)
	at com.facebook.presto.execution.scheduler.SectionExecutionFactory.createStreamingLinkedStageExecutions(SectionExecutionFactory.java:258)
	at com.facebook.presto.execution.scheduler.SectionExecutionFactory.createStreamingLinkedStageExecutions(SectionExecutionFactory.java:235)
	at com.facebook.presto.execution.scheduler.SectionExecutionFactory.createStreamingLinkedStageExecutions(SectionExecutionFactory.java:235)
	at com.facebook.presto.execution.scheduler.SectionExecutionFactory.createSectionExecutions(SectionExecutionFactory.java:179)
	at com.facebook.presto.execution.scheduler.SqlQueryScheduler.createStageExecutions(SqlQueryScheduler.java:380)
	at com.facebook.presto.execution.scheduler.SqlQueryScheduler.<init>(SqlQueryScheduler.java:248)
	at com.facebook.presto.execution.scheduler.SqlQueryScheduler.createSqlQueryScheduler(SqlQueryScheduler.java:178)
	at com.facebook.presto.execution.SqlQueryExecution.createQueryScheduler(SqlQueryExecution.java:685)
	at com.facebook.presto.execution.SqlQueryExecution.lambda$start$3(SqlQueryExecution.java:501)
	at com.facebook.presto.common.RuntimeStats.lambda$recordWallAndCpuTime$9(RuntimeStats.java:171)
	at com.facebook.presto.common.RuntimeStats.recordWallAndCpuTime(RuntimeStats.java:158)
	at com.facebook.presto.common.RuntimeStats.recordWallAndCpuTime(RuntimeStats.java:170)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:501)
	at com.facebook.presto.$gen.Presto_0_297_SNAPSHOT_2676aa3__0_297_SNAPSHOT____20260112_061124_1.run(Unknown Source)
	at com.facebook.presto.execution.SqlQueryManager.createQuery(SqlQueryManager.java:326)
	at com.facebook.presto.dispatcher.LocalDispatchQuery.lambda$startExecution$8(LocalDispatchQuery.java:210)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

## Motivation and Context
Union of table function leaf operators resulted in a multi split source,
source distribution stage. We decided that the best fix would be to
treat leaf operators like table scans, and not combine them into a
single operation. This would keep the source distribution the same as
before.

## Impact
Now able to union leaf table function operations.

## Test Plan
Added additional tests to TestSequenceFunction.java to cover these
scenarios.

```
== NO RELEASE NOTE ==
```