Fix HashTable::enableRangeWhereCan (#1253)
Summary:
This is a fix for an error in HashAggregation that occurred under a very specific set of conditions. The error is:

```
VeloxRuntimeError: multiplier != VectorHasher::kRangeTooLarge (-1 vs. 18446744073709551615)
   ...
   at Unknown.# 2  facebook::velox::exec::HashTable<false>::setHasherMode(...)
   at Unknown.# 3  facebook::velox::exec::HashTable<false>::decideHashMode(...)
   at Unknown.# 4  facebook::velox::exec::GroupingSet::addInputForActiveRows(...)
   at Unknown.# 5  facebook::velox::exec::HashAggregation::addInput(...)
```

It was triggered by a rounding error in HashTable::enableRangeWhereCan.

HashTable::decideHashMode looks at the statistics about the grouping keys to
decide optimal hash mode: kHash, kArray, or kNormalizedKey. In particular, it
looks at the range and number of distinct values (ndv) for each grouping key.

kArray is possible if the product of ndvs or ranges of all the keys is less than
2M. In this case it is possible to map a set of key values into a single
integer in [0, 2M] range. That integer because the index into array of
accumulators.

kNormalizedKey is possible if the product of ndvs or ranges of all the keys is
less than max 64-bit integer. In this case it is possible to map a set of key
values into a single 64-bit integer and use it as a single (normalized) key.
This optimization is useful because hashing and comparing single integer is
more efficient then hashing and comparing multiple values.

See
https://facebookincubator.github.io/velox/develop/aggregations.html#adaptive-array-based-aggregation
for more details about these optimizations.

In kArray and kNormalizedKey modes, each key value is mapped to a value ID which
is calculated either using range or distinct values. If using range, the value
ID is calculated as value - min. If using distinct values, each value is
assigned a sequential number which becomes the value ID.

For some keys only range or distinct values are possible, but for others both
range and distinct values are viable. For such keys, HashTable::decideHashMode
needs to choose whether to use range or distinct values. Range is used if range
< ndvs * 20 or if using range would not cause the product of ranges / ndvs to
overflow.

HashTable::enableRangeWhereCan contains the logic for checking whether using
range instead of ndv is possible. Let's say there are 3 keys, such that ndv1 *
ndv2 * ndv3 < max-64-int. HashTable::enableRangeWhereCan would check if
switching key 1 from ndv to range would not cause an overflow, i.e. range1 *
ndv2 * ndv3 would still be less than max-64-int. It would also check that for
keys 2 and 3.

To account for slight variations in the data coming in future batches, HashTable
adds a reserve to each range and ndv using 1.5 multiplier. I.e. the actual
product is calculated as safeMul(ndv1 * 1.5) * safeMul(ndv2 * 1.5) * safeMul
(ndv3 * 1.5) or safeMul(range1 * 1.5) * safeMul(ndv2 * 1.5) * safeMul
(ndv3 * 1.5), where safeMul is a helper function that checks for uint64_t
overflow and returns max uint64_t if it happens. The inputs to safeMul are
auto-casted to uint64_t.

The original implementation of HashTable::enableRangeWhereCan was calculating
the new product as safeMul(range1, originalProduct / ndv1). This calculation is
not the same as safeMul(range1 * 1.5) * safeMul(ndv2 * 1.5) * safeMul
(ndv3 * 1.5) and the discrepancy triggered the error.

Pull Request resolved: https://github.com/facebookincubator/velox/pull/1253

Reviewed By: spershin

Differential Revision: D35036367

Pulled By: mbasmanova

fbshipit-source-id: 89cc4f7e3499a7322941df1a24d58bf62f942c58