Fix CUBE aggregation over distinct inputs when input is empty
Summary:
Aggregations over distinct inputs were failing when input was empty and grouping sets included global grouping sets.

For example,

```
SELECT count(DISTINCT a)
FROM t
WHERE c % 2 > 10 -- always false
GROUP BY CUBE(b)
```

was failing with

```
VeloxRuntimeError: index < childrenSize_ (2 vs. 1) Trying to access non-existing child in RowVector: [ROW ROW<count:BIGINT>: 1 elements, no nulls]
```

Aggregation over empty set of rows for a 'global grouping set' must produce
a single row with "default" value for the aggregation (e.g. 0 for count, NULL for min).

This logic to compute "default" value resides in
GroupingSet::getDefaultGlobalGroupingSetOutput which re-uses
GroupingSet::getGlobalAggregationOutput.

getGlobalAggregationOutput is designed to be used for global aggregations
(when there are no grouping keys), but when called from
getDefaultGlobalGroupingSetOutput there are grouping keys.
getDefaultGlobalGroupingSetOutput used to "pretend" there are no grouping keys,
but modifying the 'result' vector to remove grouping keys, but that caused
failures when passing modified 'result' to TypedDistinctAggregations. The fix
is to avoid modifying 'result' vector and instead rely on AggregationInfo
struct that provides a mapping from an aggregation to a column in result
vector.

Fixes https://github.com/facebookincubator/velox/issues/8900

Reviewed By: xiaoxmeng

Differential Revision: D54330514

fbshipit-source-id: 076f217b8248dd107a52f21ddaa53b32ee2fd23e