Add dummy class to deploy presto-native-tests module (#25328)
## Description

When release 0.293, there   is an error when publishing maven artifacts,
cherry-pick @ZacBlanco 's fix from release 0.292

```
Error:  Rule failure while trying to close staging repository with ID "comfacebook-4054".
Error:  
Error:  Nexus Staging Rules Failure Report
Error:  ==================================
Error:  
Error:  Repository "comfacebook-4054" failures
Error:    Rule "javadoc-staging" failures
Error:      * Missing: no main jar artifact found in folder '/com/facebook/presto/presto-native-tests/0.293'
Error:    Rule "sources-staging" failures
Error:      * Missing: no main jar artifact found in folder '/com/facebook/presto/presto-native-tests/0.293'
Error:  
Error:  
Error:  Cleaning up local stage directory after a Rule failure during close of staging repositories: [comfacebook-4054]
Error:   * Deleting context ***.properties
Error:  Cleaning up remote stage repositories after a Rule failure during close of staging repositories: [comfacebook-4054]
Error:   * Not dropping failed staging repository with ID "comfacebook-4054" (Rule failure during close of staging repositories: [comfacebook-4054]).
Error:  Remote staging finished with a failure: Staging rules failure!
```

## Motivation and Context


## Impact
Release

## Test Plan
Tested with release 0.293

## Contributor checklist

- [ ] Please make sure your submission complies with our [contributing
guide](https://github.com/prestodb/presto/blob/master/CONTRIBUTING.md),
in particular [code
style](https://github.com/prestodb/presto/blob/master/CONTRIBUTING.md#code-style)
and [commit
standards](https://github.com/prestodb/presto/blob/master/CONTRIBUTING.md#commit-standards).
- [ ] PR description addresses the issue accurately and concisely. If
the change is non-trivial, a GitHub Issue is referenced.
- [ ] Documented new properties (with its default value), SQL syntax,
functions, or other functionality.
- [ ] If release notes are required, they follow the [release notes
guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [ ] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes
Please follow [release notes
guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines)
and fill in the release notes below.

```
== NO RELEASE NOTE ==
```

Co-authored-by: Zac Blanco <zac@ibm.com>