fix compile error with GCC12 (#4413)
Summary:
While compile velox as a lib from `gluten` with `GCC12.1.0`, we got following two errors.

Error1, because of the function `flush` do not implemented.
```
/home/opt/compiler/gcc-12/bin/../lib/gcc/x86_64-pc-linux-gnu/12.1.0/../../../../x86_64-pc-linux-gnu/bin/ld:
../../releases/libvelox.so: undefined reference to `facebook::strings::ByteSinkBuffer::flush()
```

Error2, maybe GCC12 is not smart enough, it got wrong implementation of `std::optional::value` function
```
In file included from /ssd1/zhuxiaoli01/codes/baidu/third-party/gluten/cpp/../ep/build-velox/build/velox_ep/velox/vector/FlatVector.h:514,
                 from /ssd1/zhuxiaoli01/codes/baidu/third-party/gluten/cpp/../ep/build-velox/build/velox_ep/velox/vector/tests/utils/VectorTestBase.h:21,
                 from /ssd1/zhuxiaoli01/codes/baidu/third-party/gluten/cpp/velox/tests/ArrowToVeloxTest.cc:22:
/ssd1/zhuxiaoli01/codes/baidu/third-party/gluten/cpp/../ep/build-velox/build/velox_ep/velox/vector/FlatVector-inl.h: In instantiation of ‘std::unique_ptr<facebook::velox::SimpleVector<long unsigned int> > facebook::velox::FlatVector<T>::hashAll() const [with T = facebook::velox::IntervalDayTime]’:
/ssd1/zhuxiaoli01/codes/baidu/third-party/gluten/cpp/../ep/build-velox/build/velox_ep/velox/vector/FlatVector-inl.h:80:41:   required from here
/ssd1/zhuxiaoli01/codes/baidu/third-party/gluten/cpp/../ep/build-velox/build/velox_ep/velox/vector/FlatVector-inl.h:103:35: error: passing ‘const std::optional<int>’ as ‘this’ argument discards qualifiers [-fpermissive]
  103 |       BaseVector::nullCount_.value() > 0) {
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
In file included from /ssd1/zhuxiaoli01/codes/baidu/third-party/gluten/cpp/build/releases/include/arrow/util/iterator.h:23,
                 from /ssd1/zhuxiaoli01/codes/baidu/third-party/gluten/cpp/build/releases/include/arrow/record_batch.h:28,
                 from /ssd1/zhuxiaoli01/codes/baidu/third-party/gluten/cpp/build/releases/include/arrow/ipc/reader.h:32,
                 from /ssd1/zhuxiaoli01/codes/baidu/third-party/gluten/cpp/core/jni/JniCommon.h:20,
                 from /ssd1/zhuxiaoli01/codes/baidu/third-party/gluten/cpp/core/jni/JniErrors.h:22,
                 from /ssd1/zhuxiaoli01/codes/baidu/third-party/gluten/cpp/velox/tests/ArrowToVeloxTest.cc:18:
/home/opt/compiler/gcc-12/include/c++/12.1.0/optional:999:7: note:   in call to ‘constexpr _Tp& std::optional<_Tp>::value() & [with _Tp = int]’
  999 |       value()&
      |       ^~~~~
/ssd1/zhuxiaoli01/codes/baidu/third-party/gluten/cpp/../ep/build-velox/build/velox_ep/velox/vector/FlatVector-inl.h: In instantiation of ‘std::unique_ptr<facebook::velox::SimpleVector<long unsigned int> > facebook::velox::FlatVector<T>::hashAll() const [with T = facebook::velox::Date]’:
/ssd1/zhuxiaoli01/codes/baidu/third-party/gluten/cpp/../ep/build-velox/build/velox_ep/velox/vector/FlatVector-inl.h:80:41:   required from here
/ssd1/zhuxiaoli01/codes/baidu/third-party/gluten/cpp/../ep/build-velox/build/velox_ep/velox/vector/FlatVector-inl.h:103:35: error: passing ‘const std::optional<int>’ as ‘this’ argument discards qualifiers [-fpermissive]
  103 |       BaseVector::nullCount_.value() > 0) {
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
/home/opt/compiler/gcc-12/include/c++/12.1.0/optional:999:7: note:   in call to ‘constexpr _Tp& std::optional<_Tp>::value() & [with _Tp = int]’
  999 |       value()&
      |       ^~~~~
```

Pull Request resolved: https://github.com/facebookincubator/velox/pull/4413

Reviewed By: Yuhta, laithsakka

Differential Revision: D44467355

Pulled By: pedroerp

fbshipit-source-id: 32529c8b5be117bf2c55f1cf39117c8de059d514