Remove SeekableInputStream.h include from FormatData.h (#10859)
Summary:
SeekableInputStream.h is causing the protobuf dependency to leak into Velox clients.
Move the PositionProvider class to its own file.

```
In file included from /Users/reetikaagrawal/Documents/Projects/Oss/prestodb-hivepoc/prestodb/presto-native-execution/velox/velox/connectors/hive/iceberg/IcebergSplitReader.cpp:17:
In file included from /Users/reetikaagrawal/Documents/Projects/Oss/prestodb-hivepoc/prestodb/presto-native-execution/velox/velox/connectors/hive/iceberg/IcebergSplitReader.h:21:
In file included from /Users/reetikaagrawal/Documents/Projects/Oss/prestodb-hivepoc/prestodb/presto-native-execution/velox/velox/connectors/hive/iceberg/PositionalDeleteFileReader.h:26:
In file included from /Users/reetikaagrawal/Documents/Projects/Oss/prestodb-hivepoc/prestodb/presto-native-execution/velox/velox/dwio/common/Reader.h:27:
In file included from /Users/reetikaagrawal/Documents/Projects/Oss/prestodb-hivepoc/prestodb/presto-native-execution/velox/velox/dwio/common/SelectiveColumnReader.h:22:
In file included from /Users/reetikaagrawal/Documents/Projects/Oss/prestodb-hivepoc/prestodb/presto-native-execution/velox/velox/dwio/common/FormatData.h:21:
In file included from /Users/reetikaagrawal/Documents/Projects/Oss/prestodb-hivepoc/prestodb/presto-native-execution/velox/velox/dwio/common/SeekableInputStream.h:23:
/Users/reetikaagrawal/Documents/Projects/Oss/prestodb-hivepoc/prestodb/presto-native-execution/velox/velox/dwio/common/wrap/zero-copy-stream-wrapper.h:31:10: fatal error: 'google/protobuf/io/zero_copy_stream.h' file not found
#include <google/protobuf/io/zero_copy_stream.h>
```
See https://github.com/prestodb/presto/issues/23528

Pull Request resolved: https://github.com/facebookincubator/velox/pull/10859

Reviewed By: xiaoxmeng

Differential Revision: D61936364

Pulled By: kgpai

fbshipit-source-id: ec7c913110fe0a38a5ba00a37addbfeac55e7289