Bring back OBJECT to velox_hive_connector (#3094)
Summary:
Without OBJECT label for velox_hive_conector, build of presto_server sees error like undefined reference to
HiveTableHandle::HiveTableHandle().

https://github.com/facebookincubator/velox/pull/2897 added OBJECT, but the next PR https://github.com/facebookincubator/velox/pull/2845 removed it according to change history.

Actually PR https://github.com/facebookincubator/velox/pull/2845 did not touch OBJECT according to the PR page. It is likely due to file merge of CMakeList.txt.

Pull Request resolved: https://github.com/facebookincubator/velox/pull/3094

Reviewed By: kgpai, mbasmanova

Differential Revision: D41031123

Pulled By: gggrace14

fbshipit-source-id: f50b53b01e5ab2296cd7cb8ee826cd41cf5f4916