Bring back OBJECT to add_library(velox_hive_connector). (#2897)
Summary:
Pull Request resolved: https://github.com/facebookincubator/velox/pull/2897

Removing OBJECT breaks build of executables with errors like below.
  undefined reference to HiveTableHandle::HiveTableHandle()
We suspect it is because some unused symbols get removed from
the *.a library and later cannot be found when linking an executable.

The PR that broke this:
https://github.com/facebookincubator/velox/pull/2809
Example of the linking error:
https://github.com/prestodb/presto/actions/runs/3285240930/jobs/5412120705

Reviewed By: mbasmanova

Differential Revision: D40538062

fbshipit-source-id: 3bd376de7d6b55bdebd6851aee3c7e89a732f24f