Fix map() Presto function (#906)
Summary:
Presto map() function applied to constant keys and flat values failed with an
error: `Malformed dictionary, index array is shorter than DictionaryVector`. It
also returned incorrect results when applied to flat keys and constant
values.

The problem was due to result map re-using offsets from the keys vector. When
these offsets had duplicate values (due to having duplicate keys in case of a
constant or dictionary encoding) the resulting vector could only have duplicate
entries, e.g. it could not have two entries with same keys, but different
values.

The fix is to ensure that result map uses unique offset for each row and wrap
keys and values elements in a dictionary to translate the new offsets.

Pull Request resolved: https://github.com/facebookincubator/velox/pull/906

Reviewed By: kevinwilfong

Differential Revision: D33689343

Pulled By: mbasmanova

fbshipit-source-id: e1a2203547ba65d5f42e1c1b6b5003e844a50291