Remove usage of deprecate Unsafe methods from ByteArrayUtils
Usage of deprecated methods causes NoSuchMethodError when running with Java 10+.

java.lang.NoSuchMethodError: sun.misc.Unsafe.getDouble(Ljava/lang/Object;I)D
        at com.facebook.presto.spi.block.ByteArrayUtils.getDouble(ByteArrayUtils.java:57)
        at com.facebook.presto.orc.reader.DoubleStreamReader.scan(DoubleStreamReader.java:264)
        at com.facebook.presto.orc.ColumnGroupReader.advance(ColumnGroupReader.java:473)
        at com.facebook.presto.orc.OrcRecordReader.getNextPage(OrcRecordReader.java:808)
        at com.facebook.presto.hive.orc.OrcPageSource.getNextPage(OrcPageSource.java:149)
        at com.facebook.presto.hive.HivePageSource.getNextPage(HivePageSource.java:226)
        at com.facebook.presto.operator.ScanFilterAndProjectOperator.processPageSource(ScanFilterAndProjectOperator.java:418)
        at com.facebook.presto.operator.ScanFilterAndProjectOperator.getOutput(ScanFilterAndProjectOperator.java:303)
        at com.facebook.presto.operator.Driver.processInternal(Driver.java:389)
        at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:293)
        at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:685)
        at com.facebook.presto.operator.Driver.processFor(Driver.java:286)
        at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1076)
        at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
        at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:489)
        at com.facebook.presto.$gen.Presto_0_215_117_g026543d____20190124_193910_1.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.base/java.lang.Thread.run(Thread.java:844)