Fix Ranger tests to be thread safe
Ranger test previously used a mutable state and was
causing random failures. The mutable state is
unnecessary.

```
com.facebook.presto.spi.PrestoException: Unable to fetch user groups information from ranger
at com.facebook.presto.hive.security.ranger.RangerBasedAccessControl.getGroupsForUser(RangerBasedAccessControl.java:195)
at com.facebook.presto.hive.security.ranger.RangerBasedAccessControl.checkAccess(RangerBasedAccessControl.java:217)
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (byte[])""; line: 1, column: 0]
at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1442)
at com.fasterxml.jackson.databind.ObjectReader._initForReading(ObjectReader.java:360)
```