build: fix llvm-19-exposed -Wmissing-template-arg-list-after-template-kw warning (#12433)
Summary:
Pull Request resolved: https://github.com/facebookincubator/velox/pull/12433

This avoids the following errors:

  velox/exec/VectorHasher.h:460:19: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
  velox/exec/VectorHasher.h:674:17: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]

Removing the template keyword is fine, because the compiler can deduce the type of the lambda.

Reviewed By: bikramSingh91, dmm-fb

Differential Revision: D70046455

fbshipit-source-id: 6b6a7b87f409d5c33fbfc0311eb331c350d3cefc