fix: Update numeric limits to parallel type due to compilation errors (#13657)
Summary:
Pull Request resolved: https://github.com/facebookincubator/velox/pull/13657

Update Velox check to compare against same types. Since weighted count is a double, we need to adjust the numeric limit to also a double. This was causing issues in Presto that uses a different (more strict) compiler:

```
/__w/presto/presto/presto-native-execution/velox/velox/functions/lib/QuantileDigest.h:555:7: error: implicit conversion from 'long' to 'double' changes value from 9223372036854775807 to 9223372036854775808 [-Werror,-Wimplicit-const-int-float-conversion]
      std::numeric_limits<int64_t>::max(),
```

Reviewed By: Yuhta

Differential Revision: D76060944

fbshipit-source-id: 03e0a9947293c072493fa400ef08b5f0073eefe9