Remove gtest/gtest_prod.h header from GTestMacros.h (#5945)
Summary:
GTestMacros.h is introducing a dependency on gtest library.
Duplicate a macro from gtest_prod.h and avoid this dependency.

Example:
```
In file included from /Users/wypb/data/code/apache/temp/velox/velox/connectors/hive/storage_adapters/hdfs/RegisterHdfsFileSystem.cpp:23:
In file included from /Users/wypb/data/code/apache/temp/velox/./velox/dwio/common/DataSink.h:23:
In file included from /Users/wypb/data/code/apache/temp/velox/./velox/dwio/common/DataBuffer.h:22:
In file included from /Users/wypb/data/code/apache/temp/velox/./velox/buffer/Buffer.h:27:
In file included from /Users/wypb/data/code/apache/temp/velox/./velox/common/memory/Memory.h:39:
In file included from /Users/wypb/data/code/apache/temp/velox/./velox/common/memory/Allocation.h:24:
/Users/wypb/data/code/apache/temp/velox/./velox/common/base/GTestMacros.h:24:10: fatal error: 'gtest/gtest_prod.h' file not found
#include <gtest/gtest_prod.h>
         ^~~~~~~~~~~~~~~~~~~~
```

Pull Request resolved: https://github.com/facebookincubator/velox/pull/5945

Reviewed By: amitkdutta

Differential Revision: D48008492

Pulled By: kgpai

fbshipit-source-id: 3eb3de5d4329b6c5bd3f4da3d1e0906fb308b14d