Fail plugin loading if artifact is missing
If an artifact is missing, the plugin will likely fail later
with a confusing NoClassDefFoundError. It is better to fail
early with a proper error message.