Move duckdb compile before re2 and fmt (#7722)
Summary:
After DuckDB upgrade (PR https://github.com/facebookincubator/velox/issues/6725) we see build errors:

```
/opt/gluten/ep/build-velox/build/velox_ep/_build/release/_deps/duckdb-src/src/planner/binder/expression/bind_star_expression.cpp:123:4: error: 'duckdb_re2' has not been declared
  123 |    duckdb_re2::RE2 regex(regex_str);
      |    ^~~~~~~~~~
```

If we compile re2 and fmt before DuckDB, there will cause dependency conflict.

A fix is to compile DuckDB before re2 and fmt.

Pull Request resolved: https://github.com/facebookincubator/velox/pull/7722

Reviewed By: pedroerp

Differential Revision: D51605184

Pulled By: mbasmanova

fbshipit-source-id: 54acb0a0f672abe710f6f398fa465ec46d38573c