Improve query assertion message for mismatched types
Include column types in row mismatch errors to help with debugging
failures where the columns display the same but are different types
(e.g. float vs. double or bigint vs. int)

Example new message:

java.lang.AssertionError: For query:
 SELECT array_sort(array_union(simple_real_array, ARRAY[CAST(nan() AS DOUBLE)])) FROM array_nans_table
 actual column types:
 [array(double)]
expected column types:
[array(real)]

not equal
Actual rows (6 of 6 extra rows shown, 7 rows in total):
    [[-1.0, 0.0, 1.0, NaN]]
    [[-1.0, 0.0, 1.0, NaN]]
    [[-1.0, 0.0, 1.0, NaN]]
    [[-1.0, 0.0, 1.0, NaN]]
    [[200.0, NaN, null]]
    [[NaN]]
Expected rows (6 of 6 missing rows shown, 7 rows in total):
    [[-1.0, 0.0, 1.0, NaN]]
    [[-1.0, 0.0, 1.0, NaN]]
    [[-1.0, 0.0, 1.0, NaN]]
    [[-1.0, 0.0, 1.0, NaN]]
    [[200.0, NaN, null]]
    [[NaN]]