build(cmake): Fix protobuf error during build when using Velox as a subproject (#12128)
Summary:
Error message:

```
.../cmake-build-debug/_deps/velox-src/velox/dwio/dwrf/common/wrap/dwrf-proto-wrapper.cpp:37:10: fatal error: velox/dwio/dwrf/proto/dwrf_proto.pb.cc: No such file or directory
   37 | #include "velox/dwio/dwrf/proto/dwrf_proto.pb.cc"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated
```

This is because the generated `protoc` command relies on the root CMake project path so the command will be messed up when Velox is used as a module of nother CMake project.

The patch fixes the issue.

Pull Request resolved: https://github.com/facebookincubator/velox/pull/12128

Reviewed By: sdruzkin

Differential Revision: D68448949

Pulled By: kagamiori

fbshipit-source-id: b45269fcc5f4dd4f3f3343720367d3c9a20757f5