Changes to compile with Clang15 (#10363)
Summary:
Clang needs lib atomic symbols to be resolved for a number of executables. It is added as needed.
```
/opt/rh/gcc-toolset-13/root/usr/lib/gcc/x86_64-redhat-linux/13/../../../../bin/ld: velox/exec/libvelox_exec.a(Task.cpp.o): in function `std::__atomic_base<unsigned int>::is_lock_free() const':�/opt/rh/gcc-toolset-13/root/usr/lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/atomic_base.h:460: undefined reference to `__atomic_is_lock_free'�/opt/rh/gcc-toolset-13/root/usr/lib/gcc/x86_64-redhat-linux/13/../../../../bin/ld: velox/exec/libvelox_exec.a(Task.cpp.o): in function `std::__atomic_base<long>::is_lock_free() const':�/opt/rh/gcc-toolset-13/root/usr/lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/atomic_base.h:460: undefined reference to `__atomic_is_lock_free'clang++: error: linker command failed with exit code 1 (use -v to see invocation)ninja: build stopped: subcommand failed.
```

Pull Request resolved: https://github.com/facebookincubator/velox/pull/10363

Reviewed By: pedroerp

Differential Revision: D60969348

Pulled By: xiaoxmeng

fbshipit-source-id: c2f69043bf8c75a849d29b631b7e9de576e69de4