Fix external CI build
Summary:
We cannot use `fmt::underlying` in velox because it may be built with an older version of {fmt} without this function. Replace it with a static cast to the underlying type.

Fixes

```
../.././velox/common/caching/AsyncDataCache.h:833:35: error: 'underlying' was not declared in this scope
  833 |     return formatter<int>::format(underlying(s), ctx);
      |                                   ^~~~~~~~~~

```

in https://app.circleci.com/pipelines/github/facebookincubator/velox/4361/workflows/5f5a3aea-cefb-4a7b-ba7f-7f5380f6b13a/jobs/21393.

Reviewed By: laithsakka

Differential Revision: D33776776

fbshipit-source-id: a1810cf81a2da7256b225c4d534b8a50a37008c1