Fix build failure caused by undefined reference to registerAllAggregateFunctions() (#2842)
Summary: Pull Request resolved: https://github.com/facebookincubator/velox/pull/2842

Reviewed By: mbasmanova

Differential Revision: D40371142

fbshipit-source-id: 0a76ea67b3863adef394bdc6db73269a2ce34dd8