Support decimal compare functions on different precisions and scales (#6207)
Summary:
Spark allows comparison of decimals on different precision and scales, but current Velox generates below error for this case.
> Exception: VeloxUserError
Error Source: USER
Error Code: INVALID_ARGUMENT
Reason: Scalar function greaterthan not registered with arguments: (DECIMAL(24,7), DECIMAL(21,6)). Found function registered with the following signatures:
((T,T) -> boolean)

This PR supports decimal compare functions `>, >=, ==, !=, <, <=` on different precisions and scales. The input decimals are rescaled to the same scale and then compared. For those exceeding the max precision of decimal, int256 is used to store the rescaled value.

Pull Request resolved: https://github.com/facebookincubator/velox/pull/6207

Reviewed By: amitkdutta

Differential Revision: D50870979

Pulled By: mbasmanova

fbshipit-source-id: 24bb15aed16ff045733e1d54008f5a0eea5da9b3