fix: Replace {} initialization in tests for GCC support (#14539)
Summary:
Pull Request resolved: https://github.com/facebookincubator/velox/pull/14539

TL;DR
Replace `{}` with explicit empty container and add no-error flag for virtual function overload to support gcc14 build

 ---
The following error occurs when building ToJsonTest in velox with gcc14
```
error: converting to 'std::in_place_t' from list would use explicit contructor
```

Which means that `{}` leads to copy initialization which is not allowed since `in_place_t` is marked explicit

Reviewed By: kgpai

Differential Revision: D80583340

fbshipit-source-id: 6bee27317194dd3e95e4ef6838eaca28a1a1a8b6