fix(build): Remove unused variable from the function decodeArrayElements (#11825)
Summary:
Pull Request resolved: https://github.com/facebookincubator/velox/pull/11825

Seeing the following error during build diff due to unused variable

```
Stdout: <empty>
Stderr:
fbcode/velox/functions/prestosql/ArrayIntersectExcept.cpp:143:8: error: unused variable 'decodedVector' [-Werror,-Wunused-variable]
  143 |   auto decodedVector = arrayDecoder.get();
      |        ^~~~~~~~~~~~~
1 error generated.
```

Reviewed By: mbasmanova

Differential Revision: D67071311

fbshipit-source-id: 1900968b2941684882c86e496b19f8ea9e0f8969