Fix sheduled fuzzer jobs to make removal of bias files silent. (#9586)
Summary:
This prevents errors like so : https://github.com/facebookincubator/velox/actions/runs/8802791272/job/24159384172 .

```
rm: cannot remove '*_bias_functions': No such file or directory
Error: Process completed with exit code 1.
```

Pull Request resolved: https://github.com/facebookincubator/velox/pull/9586

Reviewed By: mbasmanova

Differential Revision: D56496136

Pulled By: kgpai

fbshipit-source-id: a0a05e6885c8c66698189c2b0285258f5fe8a9cf