build: fix the remaining llvm-19-exposed -Wmissing-template-arg-list-after-template-kw warnings (#12434)
Summary:
Pull Request resolved: https://github.com/facebookincubator/velox/pull/12434

This avoids the following errors and fixes all similar instances with changes induced by running this:
  fbgs -sl 'rows.template '|xargs perl -pi -e 's{rows\.template }{rows.}'

Here are some of the errors:

  velox/expression/CastExpr-inl.h:206:19: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
  velox/expression/CastExpr-inl.h:219:19: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]

Removing the template keyword is fine, because the compiler can deduce the type of the lambda.

Reviewed By: bikramSingh91, dtolnay

Differential Revision: D70046654

fbshipit-source-id: 0bc8312f0e8e2fe5937ef69b5bbeefbe36e115d7