Enable INSERT INTO unpartitioned tables (#4251)
Summary:
This PR adds a new configuration option `immutable_partitions` which is the same as `hive.immutable-partitions` in Presto and UpdateMode::kAppend.

This enables insert into unpartitioned tables, e.g.
```sql
create table ivan_test (a int, b int);
insert into ivan_test values (1, 2), (3, 4);
```

Without the fix, insert would fail with (Presto Java runner works fine):
```
VeloxUserError:  Unpartitioned Hive tables are immutable.
```

Pull Request resolved: https://github.com/facebookincubator/velox/pull/4251

Reviewed By: amitkdutta

Differential Revision: D44885728

Pulled By: mbasmanova

fbshipit-source-id: 8202998851bc5950b7f42174597f2010054c84ab