Free the space of release action runner (#25614)
## Description


When test release action, have the error below when publishing maven
artifacts:

```
System.IO.IOException: No space left on device : '/home/runner/runners/2.326.0/_diag/Worker_20250724-124529-utc.log'    at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset) 
```
Full log:
https://github.com/unix280/presto/actions/runs/16497246602/job/46645900152

## Motivation and Context
Add more space for java and c++ action runner

## Impact
Release

## Test Plan
Test passed in my repo:
https://github.com/unix280/presto/actions/runs/16502179432

## Contributor checklist

- [ ] Please make sure your submission complies with our [contributing
guide](https://github.com/prestodb/presto/blob/master/CONTRIBUTING.md),
in particular [code
style](https://github.com/prestodb/presto/blob/master/CONTRIBUTING.md#code-style)
and [commit
standards](https://github.com/prestodb/presto/blob/master/CONTRIBUTING.md#commit-standards).
- [ ] PR description addresses the issue accurately and concisely. If
the change is non-trivial, a GitHub Issue is referenced.
- [ ] Documented new properties (with its default value), SQL syntax,
functions, or other functionality.
- [ ] If release notes are required, they follow the [release notes
guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [ ] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes

```
== NO RELEASE NOTE ==
```