Fix a binding issue in presto-verifier
The bindings are in SourceQueryModule.java, but the error complains
about VerifierModule.java. Move the bindings to VerifierModule.java.

com.google.inject.CreationException: Unable to create injector, see
the following errors:
1) Explicit bindings are required and
  com.facebook.presto.verifier.source.SnapshotQueryConsumer is not
  explicitly bound. while locating
  com.facebook.presto.verifier.source.SnapshotQueryConsumer for
  the 2nd parameter of
  com.facebook.presto.verifier.framework.VerificationManager.<init>
  (VerificationManager.java:133) at
  com.facebook.presto.verifier.framework.VerifierModule.setup
  (VerifierModule.java:130)
2) Explicit bindings are required and
  com.facebook.presto.verifier.source.SnapshotQuerySupplier is not
  explicitly bound. while locating
  com.facebook.presto.verifier.source.SnapshotQuerySupplier for
  the 3rd parameter of
  com.facebook.presto.verifier.framework.VerificationManager.<init>
  (VerificationManager.java:133) at
  com.facebook.presto.verifier.framework.VerifierModule.setup
  (VerifierModule.java:130)