Handle the scalar subqueries for unnest
The query fails at planning stage due to illegal state:
```
presto:sf1> select * from (select 1) cross join unnest((select array[1])) AS T(x);
Query 20220223_215553_00017_e3qbq failed: Unexpected subquery expression in logical plan: (SELECT ARRAY[1]

)
java.lang.IllegalStateException: Unexpected subquery expression in logical plan: (SELECT ARRAY[1]

)

```
The fix is to detect nested scalar query at the query analysis stage.
The result will look like:

```
presto:sf1> select * from (select 1) cross join unnest((select array[1])) AS T(x);
Query 20220224_222704_00016_suqrw failed: line 1:37: Scalar subqueries in UNNEST are not supported
com.facebook.presto.sql.analyzer.SemanticException: line 1:37: Scalar subqueries in UNNEST are not supported
```