refactor: Fix deprecated errors when using shared_ptr::unique() (#11318)
Summary:
After the macOS CommandLineTools SDK15  (with Clang16), the new shared_ptr.h now issues the deprecated warnings  for C++17 when using the shared_ptr::unique function. This function is removed for C++20.

The solution is to replace the function with the actual implementation using use_count.

Example error:
```
/Users/czentgr/gitspace/velox/velox/vector/BaseVector.cpp:604:14: error: 'unique' is deprecated [-Werror,-Wdeprecated-declarations]
  if (result.unique() && !isUnknownType) {
             ^
/Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/usr/include/c++/v1/__memory/shared_ptr.h:730:3: note: 'unique' has been explicitly marked deprecated here
  _LIBCPP_DEPRECATED_IN_CXX17 _LIBCPP_HIDE_FROM_ABI bool unique() const _NOEXCEPT { return use_count() == 1; }
  ^
/Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/usr/include/c++/v1/__config:1022:41: note: expanded from macro '_LIBCPP_DEPRECATED_IN_CXX17'
#    define _LIBCPP_DEPRECATED_IN_CXX17 _LIBCPP_DEPRECATED
```

Resolves: https://github.com/facebookincubator/velox/issues/11342

Pull Request resolved: https://github.com/facebookincubator/velox/pull/11318

Reviewed By: Yuhta

Differential Revision: D65420246

Pulled By: mbasmanova

fbshipit-source-id: bde61c88c03303b8d9b11e10c57efb87bf71abe9