Use orderable type in Spark max_by and min_by (#10525)
Summary:
Fixes below exception noticed when running aggregate fuzzer test. Spark's
`max_by` and `min_by` do not support ordering on map type.

```
org.apache.spark.sql.AnalysisException: [DATATYPE_MISMATCH.INVALID_ORDERING_TYPE] Cannot resolve "min_by(c0, c1)" due to data type mismatch: The `min_by` does not support ordering on type "MAP<TIMESTAMP_NTZ, TINYINT>".; line 1 pos 15;
'Aggregate [g0#33927, g1#33928], [g0#33927, g1#33928, min_by(c0#33925, c1#33926) AS a0#33924]
+- SubqueryAlias tmp
   +- View (`tmp`, [c0#33925,c1#33926,g0#33927,g1#33928])
      +- Project [cast(c0#33929 as struct<f0:bigint>) AS c0#33925, cast(c1#33930 as map<timestamp_ntz,tinyint>) AS c1#33926, cast(g0#33931 as struct<f0:boolean>) AS g0#33927, cast(g1#33932 as struct<f0:boolean>) AS g1#33928]
         +- Project [c0#33929, c1#33930, g0#33931, g1#33932]
            +- Relation [c0#33929,c1#33930,g0#33931,g1#33932] parquet
```

Pull Request resolved: https://github.com/facebookincubator/velox/pull/10525

Reviewed By: Yuhta

Differential Revision: D60145895

Pulled By: kevinwilfong

fbshipit-source-id: 3dec301d4d94c8453ba80306916a13c808414cef