Fix find_package and linking for 'gtest' library (#10422)
Summary:
Fixes https://github.com/facebookincubator/velox/issues/10421

1. Use "GTest"(not `"gtest"` or `"GTEST"`) in `find_package` to solve
   the following warning:

```
CMake Warning at CMake/ResolveDependency.cmake:70 (find_package):
  By not providing "Findgtest.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "gtest", but
  CMake did not find one.

  Could not find a package configuration file provided by "gtest" with any of
  the following names:

    gtestConfig.cmake
    gtest-config.cmake

  Add the installation prefix of "gtest" to CMAKE_PREFIX_PATH or set
  "gtest_DIR" to a directory containing one of the above files.  If "gtest"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:542 (resolve_dependency)
```

2. Use `GTest::gtest` and `Gtest::gtest_main` in the
   `target_link_libraries` to solve the following error when 'gtest' is
   pre-installed(not using the BUNDLED way). See [1]

```
ld: library not found for -gtest
```

3. Finally, because the compilation error of the precompiled 'gtest'
library has been solved, we can pre-install the 'gtest' library
in setup-macos.sh.

[1] https://cmake.org/cmake/help/v3.30/module/FindGTest.html

Pull Request resolved: https://github.com/facebookincubator/velox/pull/10422

Reviewed By: pedroerp

Differential Revision: D61135221

Pulled By: xiaoxmeng

fbshipit-source-id: 4963efcbb154e06cd413c707158255804a23c271