fix(UUID): Incorrect results when cast between UUID and VARBINARY (#12633)
Summary:
The support for cast between UUID and VARBINARY was added in  https://github.com/facebookincubator/velox/issues/12544. However, there is a mismatch in the results between Prestissimo and Presto Java, which results in the following e2e test failure in https://github.com/prestodb/presto/pull/23301.
```
java.lang.AssertionError: For query:
SELECT CAST(CAST(c_uuid AS uuid) AS VARBINARY) FROM tmp_presto_68ac2ed72d41449bba7c9de1f0530413
actual column types:
[varbinary]
expected column types:
[varbinary]

not equal
Actual rows (4 of 4 extra rows shown, 5 rows in total):
[java.nio.HeapByteBuffer[pos=0 lim=36 cap=36]]
[java.nio.HeapByteBuffer[pos=0 lim=36 cap=36]]
[java.nio.HeapByteBuffer[pos=0 lim=36 cap=36]]
[java.nio.HeapByteBuffer[pos=0 lim=36 cap=36]]
Expected rows (4 of 4 missing rows shown, 5 rows in total):
[java.nio.HeapByteBuffer[pos=0 lim=16 cap=16]]
[java.nio.HeapByteBuffer[pos=0 lim=16 cap=16]]
[java.nio.HeapByteBuffer[pos=0 lim=16 cap=16]]
[java.nio.HeapByteBuffer[pos=0 lim=16 cap=16]]
```

The reason is that https://github.com/facebookincubator/velox/issues/12544 called the castToString and castFromString functions for VARBINARY which is incorrect. Although VARCHAR and VARBINARY are both represented by StringView, we don't need the lexical cast for VARBINARY.
This PR will fix this issue.

Pull Request resolved: https://github.com/facebookincubator/velox/pull/12633

Reviewed By: kagamiori

Differential Revision: D72256180

Pulled By: amitkdutta

fbshipit-source-id: 0fc4af46dd49d80b53367021bdf6bc2a6ca21f9e