build: remove decl+set of unused variable (#12435)
Summary:
Pull Request resolved: https://github.com/facebookincubator/velox/pull/12435

This avoids the following errors:

  velox/core/PlanNode.cpp:935:15: error: variable 'dereference' set but not used [-Werror,-Wunused-but-set-variable]

Reviewed By: bikramSingh91, dtolnay

Differential Revision: D70055975

fbshipit-source-id: e507ad3c1609baac229f0531582259b4d0066336