fix: Fix ~UnknownType() used before its definition (#14310)
Summary:
Addressing the following build error:

```
[ 56%] Building CXX object _deps/velox-build/velox/buffer/CMakeFiles/velox.dir/__/common/caching/SsdCache.cpp.o
In file included from /velox4j/src/main/cpp/build/_deps/velox-src/./velox/common/memory/ByteStream.h:20,
                 from /velox4j/src/main/cpp/build/_deps/velox-src/./velox/common/memory/HashStringAllocator.h:20,
                 from /velox4j/src/main/cpp/build/_deps/velox-src/./velox/common/base/BigintIdMap.h:22,
                 from /velox4j/src/main/cpp/build/_deps/velox-src/velox/common/base/BigintIdMap.cpp:17:
/velox4j/src/main/cpp/build/_deps/velox-src/./velox/type/Type.h: In static member function 'static std::shared_ptr<const facebook::velox::UnknownType> facebook::velox::TypeFactory<facebook::velox::TypeKind::UNKNOWN>::create()':
/velox4j/src/main/cpp/build/_deps/velox-src/./velox/type/Type.h:1489:34: error: 'virtual constexpr facebook::velox::UnknownType::~UnknownType()' used before its definition
 1489 |     static constexpr UnknownType kInstance;
      |                                  ^~~~~~~~~
gmake[3]: *** [_deps/velox-build/velox/buffer/CMakeFiles/velox.dir/__/common/base/BigintIdMap.cpp.o] Error 1
```

Fixes https://github.com/facebookincubator/velox/issues/14309

Caused by https://github.com/facebookincubator/velox/pull/14177

Pull Request resolved: https://github.com/facebookincubator/velox/pull/14310

Reviewed By: amitkdutta

Differential Revision: D79455729

Pulled By: kKPulla

fbshipit-source-id: b1da765f2c0b5037d77abd786dfada939b7fe20a