Upgrade to ASM 5.2
Fixes an issue due to invalid bytecode when invoking static interface
methods in Java 9, which has stricter verification.

    java.lang.IncompatibleClassChangeError: Method com.facebook.presto.operator.project.PageFilter.positionsArrayToSelectedPositions([ZI)Lcom/facebook/presto/operator/project/SelectedPositions; must be InterfaceMethodref constant
        at com.facebook.presto.$gen.PageFilter_35.filter(Unknown Source)
        at com.facebook.presto.operator.project.DictionaryAwarePageFilter.filter(DictionaryAwarePageFilter.java:87)
        at com.facebook.presto.operator.project.PageProcessor.process(PageProcessor.java:81)
        ...

Relates to https://bugs.openjdk.java.net/browse/JDK-8147755