Make 'function not registered' a user error
Summary:
Missing features should be reported as user errors, not system errors.

```
VeloxRuntimeError:  Scalar function name not registered: presto.default.at_timezone
```

After this change, the message about would use VeloxUserError.

bypass-github-export-checks

Reviewed By: vermapratyush

Differential Revision: D46391342

fbshipit-source-id: 895d2b08c34282b4232af5ebcd44c4e08abe3afc