Fix integer overflow in newBlockBuilderLike()
When newBlockBuilderLike() is called on BlockBuilders for complex types,
toIntExact() could throw "Integer Overflow" exception when the expected
new size exceeds integer boundary. Example stack trace is as follows:

java.lang.ArithmeticException: integer overflow
at java.base/java.lang.Math.toIntExact(Math.java:1071)
at com.facebook.presto.common.block.VariableWidthBlockBuilder.
    newBlockBuilderLike(VariableWidthBlockBuilder.java:393)

This commit fixes the problem by introducing a new method
calculateBlockResetSize() that calculates the new size and bound it
by MAX_ARRAY_SIZE.